### ISSUE TITLE
Hazelcast-Kubernetes-bootstrapper 3.8.1: Error: Invalid or corrupt jarfile /bootstrapper.jar

### ISSUE THREAD

**Issue by oscerd** [pires/hazelcast-kubernetes-bootstrapper#19]
I was trying to use the latest 3.8.1 image in to the hazelcast-kubernetes deployment.yaml file.

Actually I get: Error: Invalid or corrupt jarfile /bootstrapper.jar

**Comment by pires** [comment]
Can you download it the JAR from here and try it? https://github.com/pires/hazelcast-kubernetes-bootstrapper/releases

**Comment by oscerd** [comment]
As a quick test I tried to download the jar and run java -jar and it works. Not sure if you need to tag the image again.

**Comment by pires** [comment]
Most probably.

**Comment by pires** [comment]
Done, can you try?

**Comment by oscerd** [comment]
Same error.

**Comment by oscerd** [comment]
I'll investigate a bit.

**Comment by pires** [comment]
I'm somewhat busy right now so keep me posted or ping me over the weekend.

**Comment by oscerd** [comment]
I didn't find something really suspicious, by the way 3.8.2 has been released.

**Comment by pires** [comment]
By the way, this error should be moved to the project where the container image is built.
