### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by Kashomon** [pires/hazelcast-kubernetes-bootstrapper#9]
While debugging some flakey test failures in Kuberenetes for Hazelcast, we found the following lines:

```java
    final TcpIpConfig tcpCfg = new TcpIpConfig();
    nodes.parallelStream().forEach(tcpCfg::addMember);
```

This looks like a concurrency bug, since TcpIpConfig is not thread safe. Could you patch the code? FWIW, the parallel streaming here seems like overkill for what this is doing. Just using stream would be safer.

Relevant issue in kubernetes: https://github.com/kubernetes/kubernetes/issues/30672

**Comment by pires** [comment]
I agree. I will pick the first thing in the morning and update Hazelcast version as well.

Thank you for reporting.

**Comment by Kashomon** [comment]
Also, I'm not sure if this is a problem here, but calling parallel streams from parallel streams can cause weird deadlocks: e.g., http://christian-fries.de/blog/files/2014-nested-java-8-parallel-foreach.html

From your code: 

```java
          endpoints.subsets.parallelStream().forEach(subset -> {
            subset.addresses.parallelStream().forEach(
                addr -> hazelcastEndpoints.add(addr.ip));
          });
```

**Comment by mikedanese** [comment]
I'd say just use s/parallelStreams()/streams()/ everywhere :)

**Comment by pires** [comment]
Updated instructions at https://github.com/pires/hazelcast-kubernetes.

I have moved to Deployments and upgraded to Hazelcast 3.7.

**Comment by mikedanese** [comment]
Thanks!
